/** 新匯入題 36–50 */
export default [
  {
    id: "nb036",
    stem: "36. 關於相關性的敘述，下列哪一項為因果關係？",
    type: "single",
    options: ["買了啤酒要買尿布", "天蠍座的人更容易成功", "喝紅酒可以延緩衰老", "下雨要撐傘"],
    referenceAnswer: "下雨要撐傘",
    score: 2,
    image: null,
  },
  {
    id: "nb037",
    stem: "37. 關於長條圖的敘述，下列哪些正確？(複選)",
    type: "multi",
    options: [
      "長條圖是表示數值資料最常用的統計圖",
      "長條圖是表示質性資料最常用的統計圖",
      "長條圖中的位置並沒有一定的順序",
      "長條圖的長條是連續且緊密貼近的",
    ],
    referenceAnswer: "長條圖是表示質性資料最常用的統計圖",
    score: 2,
    image: null,
  },
  {
    id: "nb038",
    stem: "38. 下列哪一項不是用來衡量集中趨勢的統計量？",
    type: "single",
    options: ["變異數", "眾數", "平均數", "中位數"],
    referenceAnswer: "變異數",
    score: 2,
    image: null,
  },
  {
    id: "nb039",
    stem: "39. 異常值通常是指一個偶發的數值，與其他的測量值相差甚遠，可使用下列哪一項統計量判別異常值？",
    type: "single",
    options: ["標準差", "相關係數", "判定係數", "變異係數"],
    referenceAnswer: "標準差",
    answerNote: "實務上亦常以 IQR／箱型圖判別；若答案以教師講義為準。",
    score: 2,
    image: null,
  },
  {
    id: "nb040",
    stem: "40. 集群與分類的不同在於，集群所要求劃分的類是未知的。 集群分 析計算方法主要有：階層的方法（hierarchical method）、分割方 法（partitioning method）、基於密度的方法（density-based method）、基於網格的方法（grid-based method）、基於模型的方 法（model-based method）等。下列哪些演算法是利用統計學定義 的距離進行度量？(複選)",
    type: "multi",
    options: [
      "階層的方法（hierarchical method）",
      "基於模型的方法（model-based method）",
      "基於密度的方法（density-based method）",
      "分割方法（partitioning method）",
    ],
    referenceAnswer:
      "階層的方法（hierarchical method）；基於密度的方法（density-based method）；分割方法（partitioning method）",
    score: 2,
    image: null,
  },
  {
    id: "nb041",
    stem: "41. 關於集群分析的敘述，下列哪一項錯誤？",
    type: "single-wrong",
    options: [
      "同群組內的個體相似性高，不同群組的個體相似性低",
      "集群分析為一種非監督式學習的過程",
      "集群分析需要按照相似性來分組",
      "可以利用集群分析，將學生姓名的首字母組成不同的組別",
    ],
    referenceAnswer: "可以利用集群分析，將學生姓名的首字母組成不同的組別",
    score: 2,
    image: null,
  },
  {
    id: "nb042",
    stem: "42. 關於主成分分析的敘述，下列哪一項錯誤？",
    type: "single-wrong",
    options: [
      "主成分分析適用於分析變量的各種組合，包含線性和非線性的組合",
      "主成分分析的優點是能夠實現資料的維度縮減",
      "主成分分析之後，各主成分會失去原始變量的業務意義",
      "主成分之間互不相關",
    ],
    referenceAnswer: "主成分分析適用於分析變量的各種組合，包含線性和非線性的組合",
    score: 2,
    image: null,
  },
  {
    id: "nb043",
    stem: "43. 購物籃分析所得出的關聯規則，下列哪些正確？(複選)",
    type: "multi",
    options: [
      "可以提供關於產品間被同時購買的有用資訊",
      "可用以調整商品擺設及交叉銷售的設計，藉以增加商店的銷售收入",
      "可以進行相關產品推薦或者挑選相應的關聯產品進行精準行銷",
      "可以尋找更多潛在的目標客戶",
    ],
    referenceAnswer:
      "可以提供關於產品間被同時購買的有用資訊；可用以調整商品擺設及交叉銷售的設計，藉以增加商店的銷售收入；可以進行相關產品推薦或者挑選相應的關聯產品進行精準行銷；可以尋找更多潛在的目標客戶",
    score: 2,
    image: null,
  },
  {
    id: "nb044",
    stem: "44. 下列哪一項不是資料視覺化圖形？",
    type: "single",
    options: [
      "散佈圖（scatter plot）",
      "儀表板（dashboard）",
      "甘特圖（Gantt chart）",
      "社會網路圖（Social Network Graph, SNG）",
    ],
    referenceAnswer: "儀表板（dashboard）",
    answerNote: "若課程將儀表板視為「整合呈現」而非單一圖形，此為常見考法。",
    score: 2,
    image: null,
  },
  {
    id: "nb045",
    stem: "45. 將原始資料進行清理、變換、縮減…等，是在下列哪一步驟中的任務？",
    type: "single",
    options: ["資料前處理", "頻繁物項集探勘", "資料探勘流程", "分類和預測"],
    referenceAnswer: "資料前處理",
    score: 2,
    image: null,
  },
  {
    id: "nb046",
    stem: "46. 關於 NoSQL 的敘述，下列哪一項錯誤？",
    type: "single-wrong",
    options: [
      "NoSQL 的意思是「不同於一般 SQL 指令的資料庫」〈No SQL〉",
      "NoSQL 適用於不需要使用關聯模型的資料",
      "NoSQL 資料庫主要並非以關聯式資料表建構而成，所以通常不以 SQL 指令做資料操作",
      "NoSQL 資料庫一般不支援 ACID 特性",
    ],
    referenceAnswer: "NoSQL 的意思是「不同於一般 SQL 指令的資料庫」〈No SQL〉",
    answerNote: "部分選項敘述過於絕對；若與教師答案不同請以課堂為準。",
    score: 2,
    image: null,
  },
  {
    id: "nb047",
    stem: "47. 如附圖所示，關聯分析中得到了如附圖之結果，下列哪一項正確？",
    type: "single",
    options: [
      "73.3% 的交易會同時購買 honey 和 whole milk",
      "Whole Milk 是最受歡迎的商品",
      "tidbits 和 rolls / buns 的消費會互相促進",
      "購買 pudding powder 的交易中有 0.13% 會購買 whole milk",
    ],
    referenceAnswer: "",
    answerNote: "附圖檔：images/WMfWw6AY.png（請自行放入）；請依圖中支持度／信賴度判讀。",
    score: 2,
    image: "WMfWw6AY.png",
  },
  {
    id: "nb048",
    stem: "48. 下列哪一個集群（clustering）技術，最適合處理任意形狀與大小的集群問題？",
    type: "single",
    options: ["階層式集群法", "k-means", "決策樹", "以密度為基礎的集群法"],
    referenceAnswer: "以密度為基礎的集群法",
    score: 2,
    image: null,
  },
  {
    id: "nb049",
    stem: "49. 關於資料視覺化的敘述，下列哪一項錯誤？",
    type: "single-wrong",
    options: [
      "資料視覺化主要將資料、文字、圖表，轉成各種圖表與影像，使得資料較容易瞭解",
      "資料視覺化需考慮觀眾不同",
      "熱繪圖、文字雲、網路圖等都屬於資料視覺化圖形",
      "資料視覺化不可以追求絢麗",
    ],
    referenceAnswer: "資料視覺化不可以追求絢麗",
    score: 2,
    image: null,
  },
  {
    id: "nb050",
    stem: "50. 如附圖所示，試計算出附圖表格內的吉尼指數（Gini 指數），下列哪一項正確？",
    type: "single",
    options: ["1", "1.5", "0", "0.5"],
    referenceAnswer: "",
    answerNote: "附圖檔：images/WMXLg2UW.png（請自行放入）；請依圖表計算後選答。",
    score: 2,
    image: "WMXLg2UW.png",
  },
];
