/** 第三批次題 1–17 */
export default [
  {
    id: "n3-001",
    stem: "1. HDFS 會先將原始檔案切割成多個區塊（block），並將每一個區塊 複製三份，分別存入三個不同的節點，假設每一個區塊的大小是 128MB，若今日要將一個 256MB 的檔案放入 HDFS，請問會產生幾 個區塊？使用了 HDFS 多少空間？",
    type: "single",
    options: ["6 個區塊，使用了 768MB", "2 個區塊，使用了 256MB", "3 個區塊，使用了 384MB", "4 個區塊，使用了 512MB"],
    referenceAnswer: "6 個區塊，使用了 768MB",
    answerNote: "若課程將「區塊」定義為實體複本數，常見答案為 6 複本、768MB；定義不同請以教師為準。",
    score: 2,
    image: null,
  },
  {
    id: "n3-002",
    stem: "2. 資料採礦社群網站 KDNuggets 對使用者所做的調查中，下列哪一 項不是處理 Big data 的常見軟體工具？",
    type: "single",
    options: ["Word", "SQL", "R", "Python"],
    referenceAnswer: "Word",
    score: 2,
    image: null,
  },
  {
    id: "n3-003",
    stem: "3. GB, PB, TB, ZB 為四種電腦記憶體容量的單位，請問它們的大小排序，下列哪一項正確？",
    type: "single",
    options: ["ZB＞PB＞TB＞GB", "PB＞TB＞ZB＞GB", "TB＞ZB＞GB＞PB", "PB＞ZB＞GB＞TB"],
    referenceAnswer: "ZB＞PB＞TB＞GB",
    score: 2,
    image: null,
  },
  {
    id: "n3-004",
    stem: "4. 關於資料探勘流程，下列哪些敘述正確？(複選)",
    type: "multi",
    options: [
      "資料探勘通常是一次性任務，一般不需要重複循環這六個步驟",
      "資料探勘一般需要六個流程：商業理解、資料理解、資料準備、建模、評估、發佈",
      "資料探勘項目只需要資料探勘工程師即可完成",
      "資料探勘的結果評估需要從商業價值方面考慮",
    ],
    referenceAnswer: "資料探勘一般需要六個流程：商業理解、資料理解、資料準備、建模、評估、發佈；資料探勘的結果評估需要從商業價值方面考慮",
    score: 2,
    image: null,
  },
  {
    id: "n3-005",
    stem: "5. 關於量化模型，下列哪一項正確？",
    type: "single",
    options: [
      "獨立變數已知或在決策者控制之下一定是敘述性模型",
      "線性規劃屬於敘述性模型",
      "函數 f〈.〉 的型式未知且缺乏定義是預測性模型",
      "計劃評核術是規範性模型",
    ],
    referenceAnswer: "計劃評核術是規範性模型",
    score: 2,
    image: null,
  },
  {
    id: "n3-006",
    stem: "6. 在 SQL 語言中，INSERT 指令的功用，下列哪一項正確？",
    type: "single",
    options: ["新增資料", "修改資料", "刪除資料", "沒有此指令"],
    referenceAnswer: "新增資料",
    score: 2,
    image: null,
  },
  {
    id: "n3-007",
    stem: "7. 每日股票交易價格，可視為下列哪一項有序資料？",
    type: "single",
    options: ["時間（temporal）資料", "次序（sequential）資料", "空間（spatial）資料", "基因序列（genetic sequence）資料"],
    referenceAnswer: "時間（temporal）資料",
    score: 2,
    image: null,
  },
  {
    id: "n3-008",
    stem: "8. 關於 JSON（JavaScript Object Notation）格式的敘述，下列哪 一項錯誤？",
    type: "single-wrong",
    options: [
      "易於人們閱讀和編寫",
      "陣列可用大括弧｛ ｝來寫入資料",
      "是一種資料交換格式源自於 JavaScript",
      "與其他程式相容性高",
    ],
    referenceAnswer: "陣列可用大括弧｛ ｝來寫入資料",
    score: 2,
    image: null,
  },
  {
    id: "n3-009",
    stem: "9. 衣服尺寸包括大、中、小是屬於下列哪一種衡量尺度？",
    type: "single",
    options: ["比例尺度〈ratio scale〉", "名目尺度〈nominal scale〉", "區間尺度〈interval scale〉", "順序尺度〈ordinal scale〉"],
    referenceAnswer: "順序尺度〈ordinal scale〉",
    score: 2,
    image: null,
  },
  {
    id: "n3-010",
    stem: "10. 關於 NoSQL 資料庫，下列敘述哪一項錯誤？",
    type: "single-wrong",
    options: [
      "NoSQL 可以理解為 \" NotOnlySQL \"，是對不同於傳統的關 聯式資料庫（relational database）的統稱",
      "NoSQL 使用 SQL 作為查詢語言，因此具有靈活的資料模型",
      "NoSQL 資料庫都去掉了關聯式資料庫的關聯式特性，這使得資料庫更容易擴展",
      "NoSQL 資料庫都具有非常高的讀寫性能",
    ],
    referenceAnswer: "NoSQL 使用 SQL 作為查詢語言，因此具有靈活的資料模型",
    score: 2,
    image: null,
  },
  {
    id: "n3-011",
    stem: "11. 如附圖所示，下列哪一項 SQL 語法可以找出所有居住於台中市的 設計者，並依設計者姓名的字典順序降冪排列？",
    type: "single",
    options: ["選項 A", "選項 B", "選項 C", "選項 D"],
    referenceAnswer: "選項 C",
    answerNote: "附圖：WMBBEESp.png。WHERE 台中市 + ORDER BY Name DESC。",
    score: 2,
    image: "WMBBEESp.png",
  },
  {
    id: "n3-012",
    stem: "12. 結構化查詢語言（SQL）的更新資料指令，下列哪一項正確？",
    type: "single",
    options: ["RENEW", "UPDATE", "INSERT", "REVISE"],
    referenceAnswer: "UPDATE",
    score: 2,
    image: null,
  },
  {
    id: "n3-013",
    stem: "13. 結構化查詢語言（SQL）的刪除資料指令，下列哪一項正確？",
    type: "single",
    options: ["DROP", "REMOVE", "CLEAR", "DELETE"],
    referenceAnswer: "DELETE",
    score: 2,
    image: null,
  },
  {
    id: "n3-014",
    stem: "14. 下列哪一項資料不是非結構化資料？",
    type: "single",
    options: ["HTML 格式的文本資料", "XML 格式的文本資料", "空間資料", "影像資料"],
    referenceAnswer: "空間資料",
    score: 2,
    image: null,
  },
  {
    id: "n3-015",
    stem: "15. 結構化查詢語言（SQL）包含下列哪些種類？(複選)",
    type: "multi",
    options: [
      "資料控制語言（Data Control Language，DCL）",
      "資料查詢語言（Data Query Language，DQL）",
      "資料定義語言（Data Definition Language，DDL）",
      "資料操作語言（Data Manipulation Language，DML）",
    ],
    referenceAnswer:
      "資料控制語言（Data Control Language，DCL）；資料查詢語言（Data Query Language，DQL）；資料定義語言（Data Definition Language，DDL）；資料操作語言（Data Manipulation Language，DML）",
    score: 2,
    image: null,
  },
  {
    id: "n3-016",
    stem: "16. 考慮下列數據：6, 47, 49, 15, 42, 41, 7, 39, 43, 40, 36，關 於第 3 四分位數（Q3），下列哪一項正確？",
    type: "single",
    options: ["40", "41", "42", "43"],
    referenceAnswer: "43",
    score: 2,
    image: null,
  },
  {
    id: "n3-017",
    stem: "17. 將非結構化資料轉換為結構化格式，下列哪一項錯誤？",
    type: "single-wrong",
    options: [
      "文件轉為各文件與詞項的橫列縱行矩陣",
      "剖析 XML 的語法後轉換為列表（list）或表格（table）的 資料格式",
      "擷取圖片、音訊與影片中的特徵製成表格的形式",
      "將資料以 XML 格式儲存",
    ],
    referenceAnswer: "將資料以 XML 格式儲存",
    answerNote: "若教師答案不同，請以講義為準。",
    score: 2,
    image: null,
  },
];
