/** 第四批次題 1-50 */
export default [
  {
    id: "n4-001",
    stem: "1. 下列哪些不是 Hadoop 的基本組件？(複選)",
    type: "multi",
    options: ["檔案存儲系統 HDFS", "資料分析程式庫 Mahout", "分散式計算框架 MapReduce", "資料存儲系統 HIVE"],
    referenceAnswer: "資料分析程式庫 Mahout；資料存儲系統 HIVE",
    score: 2,
    image: null,
  },
  {
    id: "n4-002",
    stem: "2. Hadoop 生態圖譜系統中執行資料分散式計算框架為哪一個技術？",
    type: "single",
    options: ["HDFS", "HBase", "MapReduce", "Hive"],
    referenceAnswer: "MapReduce",
    score: 2,
    image: null,
  },
  {
    id: "n4-003",
    stem: "3. GB, PB, TB, ZB 為四種電腦記憶體容量的單位，請問它們的大小排序，下列哪一項正確？",
    type: "single",
    options: ["ZB＞PB＞TB＞GB", "PB＞TB＞ZB＞GB", "TB＞ZB＞GB＞PB", "PB＞ZB＞GB＞TB"],
    referenceAnswer: "ZB＞PB＞TB＞GB",
    score: 2,
    image: null,
  },
  {
    id: "n4-004",
    stem: "4. 關於資料科學任務集的敘述，下列哪一項錯誤？",
    type: "single-wrong",
    options: [
      "小型資料集較容易處理，且訊息揭露性較佳",
      "剖繪：描繪個體、群組或母體的典型行為",
      "集群：將一群物體中相似的個體聚集在一起，並非因為特定 的目的而驅動，故屬於監督式的學習",
      "分類及類別的機率估計：用來預測群體中的每一位顧客屬於 哪一項類別，類別集合中的類別通常為互斥的",
    ],
    referenceAnswer: "集群：將一群物體中相似的個體聚集在一起，並非因為特定 的目的而驅動，故屬於監督式的學習",
    score: 2,
    image: null,
  },
  {
    id: "n4-005",
    stem: "5. CRISP-DM 資料探勘流程包括下列六項：(1)資料準備、(2)資料理解、(3)評估與測試、(4)模式建立、(5)商業理解、(6)部署應用， 其正確流程步驟哪一項正確？",
    type: "single",
    options: ["521346", "512436", "512346", "521436"],
    referenceAnswer: "521346",
    score: 2,
    image: null,
  },
  {
    id: "n4-006",
    stem: "6. 關於 JSON 的敘述，下列哪一項錯誤？",
    type: "single-wrong",
    options: [
      "JSON 是 JavaScript 的物件表示法（JavaScript Object Notation）",
      "JSON 解析器和 JSON 資料集支援許多不同的程式語言",
      "JSON 非常易於解析",
      "JSON 文本格式在語法上與創建 JavaScript 物件的代碼不同",
    ],
    referenceAnswer: "JSON 文本格式在語法上與創建 JavaScript 物件的代碼不同",
    score: 2,
    image: null,
  },
  {
    id: "n4-007",
    stem: "7. 下列哪一項為名目尺度〈nominal scale〉？",
    type: "single",
    options: ["長度", "日期", "郵遞區號", "年級"],
    referenceAnswer: "郵遞區號",
    score: 2,
    image: null,
  },
  {
    id: "n4-008",
    stem: "8. 校務系統的關聯式資料庫中，下列哪些資料欄位（或欄位組合）可 以設定為學生資料表之主索引鍵 PK？(複選)",
    type: "multi",
    options: ["姓名、生日", "身分證字號", "學號", "電話、地址"],
    referenceAnswer: "身分證字號；學號",
    score: 2,
    image: null,
  },
  {
    id: "n4-009",
    stem: "9. 關於非結構化與結構化資料，下列哪一項正確？",
    type: "single",
    options: [
      "非結構化資料其訊息形式通常是相對固定",
      "網際網路上出現的海量資料，只有非結構化一種",
      "結構化訊息是不可以數字化的",
      "非結構化資料相對於結構化資料，從巨觀上看也是結構化訊 息的一種形式",
    ],
    referenceAnswer: "非結構化資料相對於結構化資料，從巨觀上看也是結構化訊 息的一種形式",
    score: 2,
    image: null,
  },
  {
    id: "n4-010",
    stem: "10. 下列哪一項是非結構化資料庫儲存資料的方式？",
    type: "single",
    options: ["矩陣方式儲存", "表格方式儲存", "資料以鍵值對（key-value pair）的方式儲存，無需事先定 義綱要", "XML 格式儲存"],
    referenceAnswer: "資料以鍵值對（key-value pair）的方式儲存，無需事先定 義綱要",
    score: 2,
    image: null,
  },
  {
    id: "n4-011",
    stem: "11. 如附圖所示，附圖為一 SQL 語法敘述，試問別名 a,b 分別指哪一 張表格？",
    type: "single",
    options: [
      "a 是 dept 資料表的別名、b 是 emp 資料表的別名",
      "a 是 empno 資料表的別名、b 是 deptno 資料表的別名",
      "a 是 emp 資料表的別名、b 是 dept 資料表的別名",
      "a 是 sal 資料表的別名、b 是 dname 資料表的別名",
    ],
    referenceAnswer: "a 是 emp 資料表的別名、b 是 dept 資料表的別名",
    score: 2,
    image: "WMR4mv1l.png",
  },
  {
    id: "n4-012",
    stem: "12. 關於關聯式資料庫中資料表的說法，下列哪些正確？(複選)",
    type: "multi",
    options: ["資料表是二維表", "資料表的行列可以互換", "資料表的單欄主索引鍵是唯一的", "資料表的主索引鍵必須是數值型"],
    referenceAnswer: "資料表是二維表；資料表的單欄主索引鍵是唯一的",
    score: 2,
    image: null,
  },
  {
    id: "n4-013",
    stem: "13. 針對屬性衡量尺度的敘述，下列哪一項正確？",
    type: "single",
    options: [
      "名目尺度（nominal scale）僅表示群或類別，例如身分證字號、瞳孔顏色、居住地、期中考排名等",
      "區間尺度（interval scale）無絕對零點，但差異或距離有意義。如日期、攝氏或華氏溫度",
      "順序尺度（ordinal scale）通常用於順序有別時，例如身 高高度（低、中、高）、河水流速、年收入排名等",
      "比例尺度（ratio scale）其有自然零點，且比率有意義， 例如克式（Kelvin）溫度、長度、時間、次數等",
    ],
    referenceAnswer: "區間尺度（interval scale）無絕對零點，但差異或距離有意義。如日期、攝氏或華氏溫度",
    score: 2,
    image: null,
  },
  {
    id: "n4-014",
    stem: "14. 關於資料屬性尺度的範例中，下列哪一項正確？",
    type: "single",
    options: ["攝氏溫度是區間尺度", "華氏溫度是比例尺度", "郵遞區號是順序尺度", "年級是名目尺度"],
    referenceAnswer: "攝氏溫度是區間尺度",
    score: 2,
    image: null,
  },
  {
    id: "n4-015",
    stem: "15. 每日股票交易價格，可視為下列哪一項有序資料？",
    type: "single",
    options: ["時間（temporal）資料", "次序（sequential）資料", "空間（spatial）資料", "基因序列（genetic sequence）資料"],
    referenceAnswer: "時間（temporal）資料",
    score: 2,
    image: null,
  },
  {
    id: "n4-016",
    stem: "16. 下列哪一項並不是將非結構化資料轉換成結構化資料？",
    type: "single",
    options: [
      "將斷詞前的文字資料轉換成文件詞項矩陣",
      "將矩陣資料轉換成熱圖",
      "將 JSON 文件轉換成表格形式",
      "將圖像（image）資料轉換成顏色代碼矩陣",
    ],
    referenceAnswer: "將矩陣資料轉換成熱圖",
    score: 2,
    image: null,
  },
  {
    id: "n4-017",
    stem: "17. 關於屬性運算性質的說法，下列哪一項錯誤？",
    type: "single-wrong",
    options: [
      "我們可以說“2 米是 1 米的 2 倍”，所以這個資料具有比例屬性",
      "我們可以說“30 攝氏度比 20 攝氏度高 10 度”，所以這 資料具有區間屬性",
      "我們可以說“代表男性的 2 大於代表女性的 1”，所以這個資料具有順序屬性",
      "我們可以說“黑色與白色不同”，所以這個資料具有名目屬性",
    ],
    referenceAnswer: "我們可以說“代表男性的 2 大於代表女性的 1”，所以這個資料具有順序屬性",
    score: 2,
    image: null,
  },
  {
    id: "n4-018",
    stem: "18. 關於主鍵（Primary Key）的敘述，下列哪些正確？(複選)",
    type: "multi",
    options: ["不考慮複合主鍵的情況下，該表格中該欄位內的值不得重複", "主鍵只能包含一個欄位", "包含多個欄位的主鍵，稱為複合主鍵（Composite Key）", "一張表內僅能有一個主鍵"],
    referenceAnswer: "不考慮複合主鍵的情況下，該表格中該欄位內的值不得重複；包含多個欄位的主鍵，稱為複合主鍵（Composite Key）；一張表內僅能有一個主鍵",
    score: 2,
    image: null,
  },
  {
    id: "n4-019",
    stem: "19. 如附圖所示，已知產品資料表：Product（ProductID, DesignDate, DesignerID），以下 SQL 指令結果，下列哪一項正 確？",
    type: "single",
    options: ["3", "4", "5", "9"],
    referenceAnswer: "5",
    score: 2,
    image: "WMd6nwUz.png",
  },
  {
    id: "n4-020",
    stem: "20. 如附圖所示，已知產品資料表：Product（ProductID, DesignDate, DesignerID），找出產品資料表中設計師編號為 2 或 3 所有資料的 SQL 指令，下列哪一項正確？",
    type: "single",
    options: [
      "SELECT * FROM Product WHERE DesignerID = 2 AND DesignerID =3",
      "SELECT * FROM Product WHERE DesignerID = 2 IN DesignerID =3",
      "SELECT * FROM Product WHERE DesignerID = 2 OR DesignerID =3",
      "SELECT * FROM Product WHERE DesignerID = 2 BOTH DesignerID =3",
    ],
    referenceAnswer: "SELECT * FROM Product WHERE DesignerID = 2 OR DesignerID =3",
    score: 2,
    image: "WMR3d8n4.png",
  },
  {
    id: "n4-021",
    stem: "21. 結構化查詢語言（SQL）的刪除資料指令，下列哪一項正確？",
    type: "single",
    options: ["DROP", "REMOVE", "CLEAR", "DELETE"],
    referenceAnswer: "DELETE",
    score: 2,
    image: null,
  },
  {
    id: "n4-022",
    stem: "22. 區間尺度（interval scale）可做下列哪些運算？(複選)",
    type: "multi",
    options: ["不等性（distinctness）運算", "順序性（order）運算", "可加性（addition）運算", "可乘性（multiplication）運算"],
    referenceAnswer: "不等性（distinctness）運算；順序性（order）運算；可加性（addition）運算",
    score: 2,
    image: null,
  },
  {
    id: "n4-023",
    stem: "23. 如附圖所示，已知產品資料表：Product（ProductID, DesignDate, DesignerID），找出產品資料表中設計日期為 2014 年 9 月 13 日（含）以前所有資料的 SQL 指令，下列哪一項正確？",
    type: "single",
    options: [
      "SELECT * FROM Product WITH DesignDate < '9/13/2014'",
      "SELECT * FROM Product WHERE DesignDate < '9/13/2014'",
      "SELECT * FROM Product WITH DesignDate <= '9/13/2014'",
      "SELECT * FROM Product WHERE DesignDate <= '9/13/2014'",
    ],
    referenceAnswer: "SELECT * FROM Product WHERE DesignDate <= '9/13/2014'",
    score: 2,
    image: "WMV5ZFbP.png",
  },
  {
    id: "n4-024",
    stem: "24. NoSQL 適用於不需要使用關聯模型的資料，近年來因大型網頁應用 程式（例如：Google、Facebook、Yahoo、Twitter 等公司的系 統）興起，下列哪一項不為其特色？",
    type: "single",
    options: [
      "採用綱要式（schema）的資料表達方式，彈性且無須太多的事前規劃，但仍可與時俱進",
      "可處理大量資料",
      "有較高的可用性，亦即可以同時多人連線，克服關聯式資料庫（RDBMS）資料鎖住（data lock）的問題",
      "縮放性（scalability）佳",
    ],
    referenceAnswer: "採用綱要式（schema）的資料表達方式，彈性且無須太多的事前規劃，但仍可與時俱進",
    score: 2,
    image: null,
  },
  {
    id: "n4-025",
    stem: "25. 關於比例（ratio）屬性值，擁有下列哪些運算性質？(複選)",
    type: "multi",
    options: ["不等性（distinctness）", "順序性（order）", "可加性（addition）", "可乘性（multiplication）"],
    referenceAnswer: "不等性（distinctness）；順序性（order）；可加性（addition）；可乘性（multiplication）",
    score: 2,
    image: null,
  },
  {
    id: "n4-026",
    stem: "26. 若隨機變數 X 具有二項分配（Binomial Distribution），成功的機率為 0.2，試驗次數為 10，則期望值與變異數分別為下列哪一 項？",
    type: "single",
    options: ["期望值 8，變異數 2.5", "期望值 8，變異數 1.6", "期望值 2，變異數 2.5", "期望值 2，變異數 1.6"],
    referenceAnswer: "期望值 2，變異數 1.6",
    score: 2,
    image: null,
  },
  {
    id: "n4-027",
    stem: "27. 如附圖所示，關於常態分配，下列敘述哪一項錯誤？",
    type: "single-wrong",
    options: ["選項 A", "選項 B", "選項 C", "選項 D"],
    referenceAnswer: "選項 C",
    score: 2,
    image: "WM9uaDA1.png",
  },
  {
    id: "n4-028",
    stem: "28. 如附圖所示，為某商品在各時期的銷售價格時，所成交的次數，成 交次數出現最多次的組別是哪一組",
    type: "single",
    options: [
      "第一組銷售價格為 5-10 時，成交次數最多",
      "第三組銷售價格為 15-20 時，成交次數最多",
      "第四組銷售價格為 20-25 時，成交次數最多",
      "第五組銷售價格為 30-35 時，成交次數最多",
    ],
    referenceAnswer: "第三組銷售價格為 15-20 時，成交次數最多",
    score: 2,
    image: "WMrpIuum.png",
  },
  {
    id: "n4-029",
    stem: "29. 下列哪些為平均數的優點？(複選)",
    type: "multi",
    options: ["資料無極端值或偏態時，具有代表性", "考慮所有觀察值，敏感度較高", "適合代數與統計推論計算", "不受極端值影響"],
    referenceAnswer: "資料無極端值或偏態時，具有代表性；考慮所有觀察值，敏感度較高；適合代數與統計推論計算",
    score: 2,
    image: null,
  },
  {
    id: "n4-030",
    stem: "30. 下列哪一項為理想上的迴歸分析運作流程？",
    type: "single",
    options: [
      "驗證資料符合模型前提假設 → 確認變數之間具有線性關係 → 執行迴歸分析 → 評估模型配適是否合適，適度校正模型",
      "確認變數之間具有線性關係 → 驗證資料符合模型前提假設 → 執行迴歸分析 → 評估模型配適是否合適，適度校正模型",
      "執行迴歸分析 → 確認變數之間具有線性關係 → 驗證資料符 合模型前提假設 → 評估模型配適是否合適，適度校正模型",
      "執行迴歸分析→ 驗證資料符合模型前提假設 → 確認變數 之間具有線性關係 → 評估模型配適是否合適，適度校正模型",
    ],
    referenceAnswer: "確認變數之間具有線性關係 → 驗證資料符合模型前提假設 → 執行迴歸分析 → 評估模型配適是否合適，適度校正模型",
    score: 2,
    image: null,
  },
  {
    id: "n4-031",
    stem: "31. 關於信賴區間的敘述，下列哪一項正確？",
    type: "single",
    options: [
      "當樣本數越大，信賴區間長度越長",
      "重複兩次蒐集資料的過程，在相同樣本數的條件下，這兩次所求得的信賴區間相同",
      "當樣本數固定的情況下，信心水準越大，信賴區間長度越長",
      "信賴區間長度與樣本數無關",
    ],
    referenceAnswer: "當樣本數固定的情況下，信心水準越大，信賴區間長度越長",
    score: 2,
    image: null,
  },
  {
    id: "n4-032",
    stem: "32. 如附圖所示，假設檢定的兩種誤差，下列哪些正確？(複選)",
    type: "multi",
    options: ["選項 A", "選項 B", "選項 C", "選項 D"],
    referenceAnswer: "選項 A；選項 B",
    score: 2,
    image: "WMBch9Yh.png",
  },
  {
    id: "n4-033",
    stem: "33. 四分位距（Interquartile Range, IQR）指的是中間多少比例的資 料？",
    type: "single",
    options: ["20 %", "30 %", "40 %", "50 %"],
    referenceAnswer: "50 %",
    score: 2,
    image: null,
  },
  {
    id: "n4-034",
    stem: "34. 如附圖所示，關於迴歸分析的敘述，下列哪一項錯誤？",
    type: "single-wrong",
    options: ["選項 A", "選項 B", "選項 C", "選項 D"],
    referenceAnswer: "選項 C",
    score: 2,
    image: "WMJviuQH.png",
  },
  {
    id: "n4-035",
    stem: "35. 關於卜瓦松分配（Poisson distribution）的敘述，下列哪一項錯 誤？",
    type: "single-wrong",
    options: [
      "在特定區間內，事件發生的平均次數固定",
      "事件發生的機率與區間的起點無關",
      "在任何區間內，事件發生彼此會互相影響",
      "在特定區間內，事件發生兩次以上的機率為 0",
    ],
    referenceAnswer: "在任何區間內，事件發生彼此會互相影響",
    score: 2,
    image: null,
  },
  {
    id: "n4-036",
    stem: "36. 迴歸模式之整體配適情況， 可由下列哪一項係數得知？",
    type: "single",
    options: ["相關係數", "判定係數", "共變異數", "中位數"],
    referenceAnswer: "判定係數",
    score: 2,
    image: null,
  },
  {
    id: "n4-037",
    stem: "37. 在單因子變異數分析之中，考慮四大飲料品牌之平均銷售量分析， 每一品牌隨機抽取 5 個樣本，下列敘述哪些正確？(複選)",
    type: "multi",
    options: [
      "組間變異 SSB〈Sum of Squares of Between〉的自由度為 3",
      "總變異的自由度為 20",
      "隨機誤差的自由度為 16",
      "如果 F 統計值大於 F 分配查表的臨界值時，則表示四大飲料品牌之平均銷售量不全相等",
    ],
    referenceAnswer: "組間變異 SSB〈Sum of Squares of Between〉的自由度為 3；隨機誤差的自由度為 16；如果 F 統計值大於 F 分配查表的臨界值時，則表示四大飲料品牌之平均銷售量不全相等",
    score: 2,
    image: null,
  },
  {
    id: "n4-038",
    stem: "38. 執行迴歸分析時理想上須先驗證資料是否遵守先決條件，下列敘述哪一項錯誤？",
    type: "single-wrong",
    options: ["以 Normal probability plot 驗證獨立性", "以 Q-Q plot 驗證常態性", "以 Modified Levene Test 驗證一致性", "以 Residual time sequence plot 驗證獨立性"],
    referenceAnswer: "以 Normal probability plot 驗證獨立性",
    score: 2,
    image: null,
  },
  {
    id: "n4-039",
    stem: "39. 如附圖所示，試計算出附圖表格內的吉尼指數（Gini 指數），下列哪一項正確？",
    type: "single",
    options: ["1", "1.5", "0", "0.5"],
    referenceAnswer: "0",
    score: 2,
    image: "WMXLg2UW.png",
  },
  {
    id: "n4-040",
    stem: "40. 關於階層集群，下列哪一項不是常用的群間距離度量？",
    type: "single",
    options: ["組平均距離（group average）法", "最短距離（single linkage）法", "最長距離（complete linkage）法", "最佳距離（optimal linkage）法"],
    referenceAnswer: "最佳距離（optimal linkage）法",
    score: 2,
    image: null,
  },
  {
    id: "n4-041",
    stem: "41. 下列哪一項不能用於比較決策樹的分類效果？",
    type: "single",
    options: [
      "通過對測試資料集的分類，得到分類準確率；然後透過統計 計算，得到決策樹分類準確率的信賴區間（confidence interval），結合兩個一起判斷效果",
      "用包含 10 個紀錄的測試資料集進行檢驗，準確率越高的效果越好",
      "比較兩個決策樹分類效果時，檢驗兩樹準確率是否在統計上有顯著差別",
      "用 k 折交叉驗證的方法比較分類效果",
    ],
    referenceAnswer: "用包含 10 個紀錄的測試資料集進行檢驗，準確率越高的效果越好",
    score: 2,
    image: null,
  },
  {
    id: "n4-042",
    stem: "42. 資料探勘中將預測結果與真實值進行比較，下列敘述哪些正確？ (複選)",
    type: "multi",
    options: [
      "對感興趣的類別作了正確的分類稱正確陽性 True Positive （TP）",
      "真陽性比率稱為特異性（specificity）",
      "對不感興趣的類別作了正確的分類稱正確陰性 True Negative（TN）",
      "真陰性比率稱為靈敏度（sensitivity）",
    ],
    referenceAnswer: "對感興趣的類別作了正確的分類稱正確陽性 True Positive （TP）；對不感興趣的類別作了正確的分類稱正確陰性 True Negative（TN）",
    score: 2,
    image: null,
  },
  {
    id: "n4-043",
    stem: "43. 如附圖所示，附圖中交易資料計算 { whole milk , other vegetables} 的支持度，下列哪一項正確？",
    type: "single",
    options: ["0.6", "0.3", "0.2", "0.18"],
    referenceAnswer: "0.2",
    score: 2,
    image: "WMTjLiOC.png",
  },
  {
    id: "n4-044",
    stem: "44. 異常值通常是指一個偶發的數值，與其他的測量值相差甚遠，可使用下列哪一項統計量判別異常值？",
    type: "single",
    options: ["標準差", "相關係數", "判定係數", "變異係數"],
    referenceAnswer: "標準差",
    score: 2,
    image: null,
  },
  {
    id: "n4-045",
    stem: "45. 關於集群分析的敘述，下列哪些正確？(複選)",
    type: "multi",
    options: [
      "集群分析是一種非監督式學習（Unsupervised learning）",
      "群內差異大，群間差異小",
      "依據個體間的相似性將樣本分成幾群互相沒有交集的群組",
      "同群組內的個體相似性高，不同群組的個體相似性低",
    ],
    referenceAnswer: "集群分析是一種非監督式學習（Unsupervised learning）；依據個體間的相似性將樣本分成幾群互相沒有交集的群組；同群組內的個體相似性高，不同群組的個體相似性低",
    score: 2,
    image: null,
  },
  {
    id: "n4-046",
    stem: "46. 下列哪一項不是資料視覺化的基本原則？",
    type: "single",
    options: ["明確視覺化的具體目標", "在圖形中盡可能呈現多樣化訊息", "考慮觀眾／聽眾的不同", "選擇合適的視覺編碼方法"],
    referenceAnswer: "在圖形中盡可能呈現多樣化訊息",
    score: 2,
    image: null,
  },
  {
    id: "n4-047",
    stem: "47. 下列哪一項不是資料視覺化圖形？",
    type: "single",
    options: ["散佈圖（scatter plot）", "儀表板（dashboard）", "甘特圖（Gantt chart）", "社會網路圖（Social Network Graph, SNG）"],
    referenceAnswer: "儀表板（dashboard）",
    score: 2,
    image: null,
  },
  {
    id: "n4-048",
    stem: "48. 關於資料縮減（Data Reduction），下列敘述哪一項錯誤？",
    type: "single-wrong",
    options: [
      "資料縮減的方法只有一種",
      "可消除資料間的相互影響，增強模型的效果",
      "資料縮減（Data Reduction）是指從原始資料中挑選出部分資料來進行分析",
      "能夠高性能地進行運算",
    ],
    referenceAnswer: "資料縮減的方法只有一種",
    score: 2,
    image: null,
  },
  {
    id: "n4-049",
    stem: "49. 關於長寬表的敘述，下列哪些正確？(複選)",
    type: "multi",
    options: ["長表變數很少，紀錄很多", "Database 的結構通常是長表", "長表指的是變數比較多紀錄比較少的資料", "任何包含離散變數的資料都不可以在長表和寬表之間自由轉換"],
    referenceAnswer: "長表變數很少，紀錄很多；Database 的結構通常是長表",
    score: 2,
    image: null,
  },
  {
    id: "n4-050",
    stem: "50. 如附圖所示，此名稱及運用的分析，下列哪一項正確？",
    type: "single",
    options: ["決策樹（Decision Tree），用在分類", "K 平均法（K-means），用在分群", "文字雲（Word Cloud），用在文字探勘（text mining）", "階層式分群（hierarchical clustering），用在分群"],
    referenceAnswer: "文字雲（Word Cloud），用在文字探勘（text mining）",
    score: 2,
    image: "WMXMXtyC.png",
  },
];
