/** 第三批次題 18–34 */
export default [
  {
    id: "n3-018",
    stem: "18. 如附圖所示，下列哪一項 SQL 語法可以找出所有設計者之最新設 計產品的日期，並顯示欄位三個：設計者編號、設計者姓名、最新 設計產品的日期？",
    type: "single",
    options: ["選項 A", "選項 B", "選項 C", "選項 D"],
    referenceAnswer: "選項 A",
    answerNote: "附圖：WMxEi6Y7.png。典型為子查詢 MAX(DesignDate) 再 JOIN Designer；若課程答案為 C 請以教師為準。",
    score: 2,
    image: "WMxEi6Y7.png",
  },
  {
    id: "n3-019",
    stem: "19. 關於 NoSQL 資料庫，下列哪一項正確？",
    type: "single",
    options: [
      "MongoDB 可以採用 BSON（Binary Format Of JSON）形式的儲存文件",
      "Redis 無法採用鍵值對（Key-Value Pair）的方式儲存",
      "鍵值儲存資料需事先定義綱要",
      "Neo4j 是以文件為基礎的儲存方式",
    ],
    referenceAnswer: "MongoDB 可以採用 BSON（Binary Format Of JSON）形式的儲存文件",
    score: 2,
    image: null,
  },
  {
    id: "n3-020",
    stem: "20. 關於資料屬性尺度的範例中，下列哪一項正確？",
    type: "single",
    options: [
      "攝氏溫度是區間尺度",
      "華氏溫度是比例尺度",
      "郵遞區號是順序尺度",
      "年級是名目尺度",
    ],
    referenceAnswer: "攝氏溫度是區間尺度",
    score: 2,
    image: null,
  },
  {
    id: "n3-021",
    stem: "21. 下列哪一項不是 SQL 語言格式？",
    type: "single",
    options: ["資料定義語言（DDL）", "資料操作語言（DML）", "資料控制語言（DCL）", "資料分析語言（DAL）"],
    referenceAnswer: "資料分析語言（DAL）",
    score: 2,
    image: null,
  },
  {
    id: "n3-022",
    stem: "22. 若欲使用 SQL 語言，找出 Product 資料表中設計日期 （designDate）為 95 年 10 月 2 日之前（包括 95 年 10 月 2 日）所有資料，建議日期格式以 '10/2/2006' 為主（'月/日/西元 年'），下列哪一項正確？",
    type: "single",
    options: [
      "SELECT * FROM Product WHERE designDate<='10/2/2006'",
      "SELECT * FROM designDate WHERE Date > 951002",
      "SELECT * FROM designDate WHERE Product <='10/2/2006'",
      "SELECT * FROM Product",
    ],
    referenceAnswer: "SELECT * FROM Product WHERE designDate<='10/2/2006'",
    score: 2,
    image: null,
  },
  {
    id: "n3-023",
    stem: "23. 如附圖所示，已知產品資料表：Product（ProductID, DesignDate, DesignerID），找出產品資料表中設計日期為 2014 年 9 月 13 日（含）以前所有資料的 SQL 指令，下列哪一項正確？",
    type: "single",
    options: [
      "SELECT * FROM Product WITH DesignDate < '9/13/2014'",
      "SELECT * FROM Product WHERE DesignDate < '9/13/2014'",
      "SELECT * FROM Product WITH DesignDate <= '9/13/2014'",
      "SELECT * FROM Product WHERE DesignDate <= '9/13/2014'",
    ],
    referenceAnswer: "SELECT * FROM Product WHERE DesignDate <= '9/13/2014'",
    answerNote: "附圖：WMV5ZFbP.png。題目選項 D 原文若缺右引號，以正確 SQL 語法為準。",
    score: 2,
    image: "WMV5ZFbP.png",
  },
  {
    id: "n3-024",
    stem: "24. 下列哪一項是非結構化資料庫儲存資料的方式？",
    type: "single",
    options: ["矩陣方式儲存", "表格方式儲存", "資料以鍵值對（key-value pair）的方式儲存，無需事先定 義綱要", "XML 格式儲存"],
    referenceAnswer: "資料以鍵值對（key-value pair）的方式儲存，無需事先定 義綱要",
    score: 2,
    image: null,
  },
  {
    id: "n3-025",
    stem: "25. 關於資料格式的敘述，下列哪些正確？(複選)",
    type: "multi",
    options: [
      "JSON 格式（JavaScript Object Notation）是一種輕量級 的資料交換格式，源自於 JavaScript",
      "HTML 格式現已成為網頁及其他領域中，在進行各種資料交 換的依循標準",
      "XML 格式是一個簡單且非常彈性的文字資料格式",
      "XML 並不是用來編排內容，而是用來描述資料，它並沒有如 同 HTML 一般的預設標籤，事實上使用者需要定義描述資料 的各種標籤",
    ],
    referenceAnswer:
      "JSON 格式（JavaScript Object Notation）是一種輕量級 的資料交換格式，源自於 JavaScript；XML 並不是用來編排內容，而是用來描述資料，它並沒有如 同 HTML 一般的預設標籤，事實上使用者需要定義描述資料 的各種標籤",
    score: 2,
    image: null,
  },
  {
    id: "n3-026",
    stem: "26. 下列哪一項為理想上的迴歸分析運作流程？",
    type: "single",
    options: [
      "驗證資料符合模型前提假設 → 確認變數之間具有線性關係 → 執行迴歸分析 → 評估模型配適是否合適，適度校正模型",
      "確認變數之間具有線性關係 → 驗證資料符合模型前提假設 → 執行迴歸分析 → 評估模型配適是否合適，適度校正模型",
      "執行迴歸分析 → 確認變數之間具有線性關係 → 驗證資料符 合模型前提假設 → 評估模型配適是否合適，適度校正模型",
      "執行迴歸分析→ 驗證資料符合模型前提假設 → 確認變數 之間具有線性關係 → 評估模型配適是否合適，適度校正模型",
    ],
    referenceAnswer: "確認變數之間具有線性關係 → 驗證資料符合模型前提假設 → 執行迴歸分析 → 評估模型配適是否合適，適度校正模型",
    score: 2,
    image: null,
  },
  {
    id: "n3-027",
    stem: "27. 如附圖所示，某輪胎工廠宣稱其生產之輪胎平均壽命至少 50,000 公里。今某一汽車修理廠欲採購其輪胎，抽取 25 個輪胎檢測其平 均壽命為 49,500 公里，標準差為 500 公里，試利用附圖資料計 算，輪胎平均壽命在 95% 的信心水準下之信賴區間，下列哪一項 正確？",
    type: "single",
    options: ["（49328.9, 49671.1）", "（49293.6, 49706.4）", "（49329.2, 49670.8）", "（49294, 49706）"],
    referenceAnswer: "（49293.6, 49706.4）",
    answerNote: "附圖：WMDCa5rQ.png。",
    score: 2,
    image: "WMDCa5rQ.png",
  },
  {
    id: "n3-028",
    stem: "28. 下列哪一項不是 Poisson 實驗的性質？",
    type: "single",
    options: [
      "在特定區間內，某事件發生的平均次數固定",
      "在特定區間內，某事件發生兩次以上的機率為 0",
      "在任何區間內，事件發生彼此不會互相影響",
      "在特定區間內，事件發生彼此會互相影響",
    ],
    referenceAnswer: "在特定區間內，事件發生彼此會互相影響",
    score: 2,
    image: null,
  },
  {
    id: "n3-029",
    stem: "29. 關於平均絕對離差（Mean Absolute Deviation, MAD）的敘述，下 列哪一項正確？",
    type: "single",
    options: [
      "其值越大，則資料的分散情況也越小",
      "觀念簡單，易於了解",
      "當資料數較多時，計算十分容易",
      "不易受極端值的影響",
    ],
    referenceAnswer: "觀念簡單，易於了解",
    score: 2,
    image: null,
  },
  {
    id: "n3-030",
    stem: "30. 執行迴歸分析時理想上須先驗證資料是否遵守先決條件，下列敘述哪一項錯誤？",
    type: "single-wrong",
    options: [
      "以 Normal probability plot 驗證獨立性",
      "以 Q-Q plot 驗證常態性",
      "以 Modified Levene Test 驗證一致性",
      "以 Residual time sequence plot 驗證獨立性",
    ],
    referenceAnswer: "以 Normal probability plot 驗證獨立性",
    score: 2,
    image: null,
  },
  {
    id: "n3-031",
    stem: "31. 常用的統計值中，平均數的優點有下列哪些？(複選)",
    type: "multi",
    options: [
      "資料無極端值或偏態時，具有代表性",
      "考慮所有觀察值，敏感度較高",
      "適合代數與統計推論計算",
      "不容易受極端值影響",
    ],
    referenceAnswer: "資料無極端值或偏態時，具有代表性；考慮所有觀察值，敏感度較高；適合代數與統計推論計算",
    score: 2,
    image: null,
  },
  {
    id: "n3-032",
    stem: "32. 關於抽樣的敘述，下列哪一項錯誤？",
    type: "single-wrong",
    options: [
      "抽樣可以做為描繪資料特徵的工具之一",
      "行政院主計處發布家庭收支調查資料為抽樣結果",
      "系統抽樣是屬於隨機抽樣方法",
      "分層抽樣是屬於非隨機抽樣方法",
    ],
    referenceAnswer: "分層抽樣是屬於非隨機抽樣方法",
    score: 2,
    image: null,
  },
  {
    id: "n3-033",
    stem: "33. 關於資料的離散程度常用三個指標：a.標準差、b.四分位距、c.變 異係數。假設有三個情境分別為：\n(1)有一個大公司和一個小公司，比較這兩個公司的業績，哪個波動更大、\n(2)用一周的訓練資 料，比較兩個同一級別的射擊選手較能發揮穩定性、\n(3)現有兩個業績相近的公司給所有員工的薪資資料。\n若要比較哪一間公司薪水 整體差距更大，下列哪一項配對正確？",
    type: "single",
    options: [
      "（1）- c、（2）- a、（3）- b",
      "（1）- a、（2）- b、（3）- c",
      "（1）- c、（2）- b、（3）- a",
      "（1）- a、（2）- c、（3）- b",
    ],
    referenceAnswer: "（1）- c、（2）- a、（3）- b",
    score: 2,
    image: null,
  },
  {
    id: "n3-034",
    stem: "34. 如附圖所示，關於常態分配，下列敘述哪一項錯誤？",
    type: "single-wrong",
    options: ["選項 A", "選項 B", "選項 C", "選項 D"],
    referenceAnswer: "選項 C",
    answerNote: "附圖：WM9uaDA1.png。μ 增大為平移，不會使常態分配「右偏」。",
    score: 2,
    image: "WM9uaDA1.png",
  },
];
