/** 新匯入題 18–35 */
export default [
  {
    id: "nb018",
    stem: "18. 如附圖所示，下列哪一項 SQL 語法可以找出所有產品編號、設計 日期、以及設計人員姓名？",
    type: "single",
    options: ["選項 A", "選項 B", "選項 C", "選項 D"],
    referenceAnswer: "",
    answerNote: "附圖檔：images/WMpKltFQ.png（請自行放入）；選項以圖中 A～D 為準。",
    score: 2,
    image: "WMpKltFQ.png",
  },
  {
    id: "nb019",
    stem: "19. 下列哪一項不屬於非結構化資料？",
    type: "single",
    options: ["語音檔", "影像檔", "電子郵件", "XML 檔"],
    referenceAnswer: "XML 檔",
    score: 2,
    image: null,
  },
  {
    id: "nb020",
    stem: "20. 非結構化訊息的敘述，下列哪一項錯誤？",
    type: "single-wrong",
    options: [
      "訊息形式相對不固定，通常是各種格式的文件（text）、影 像（image）、音訊（audio）、影片（video）",
      "非結構化相對於結構化訊息而言，從巨觀上看也是結構化訊 息的一種形式",
      "結構化訊息是可以數字化的，方便地通過電腦與資料庫技術 進行管理",
      "網際網路上出現的海量訊息，大概分為結構化和非結構化兩種",
    ],
    referenceAnswer: "非結構化相對於結構化訊息而言，從巨觀上看也是結構化訊 息的一種形式",
    score: 2,
    image: null,
  },
  {
    id: "nb021",
    stem: "21. 若要符合下述情境的 SQL 指令「找出 Product 資料表中設計日期 為 2014 年 10 月 2 日且設計者編號是 1001 的所有資料」，下列哪 一項正確？",
    type: "single",
    options: [
      "SELECT * FROM Product WHERE DesignDate = '10/2/2014' OR DesignerID =1001",
      "SELECT * FROM Product WHERE DesignDate = '10/2/2014' AND DesignerID =1001",
      "SELECT DesignDate AND DesignerID FROM Product WHERE= '10/2/2014' AND 1001",
      "SELECT DesignDate='10/2/2014' AND DesignerID =1001 FROM Product",
    ],
    referenceAnswer: "SELECT * FROM Product WHERE DesignDate = '10/2/2014' AND DesignerID =1001",
    score: 2,
    image: null,
  },
  {
    id: "nb022",
    stem: "22. 考慮下列數據：6, 47, 49, 15, 42, 41, 7, 39, 43, 40, 36，關 於第 3 四分位數（Q3），下列哪一項正確？",
    type: "single",
    options: ["40", "41", "42", "43"],
    referenceAnswer: "43",
    answerNote: "常見算法：(n+1)·3/4 列位或內插；若與課本公式不同請以教師為準。",
    score: 2,
    image: null,
  },
  {
    id: "nb023",
    stem: "23. 關於關聯式資料庫中資料表的說法，下列哪些正確？(複選)",
    type: "multi",
    options: [
      "資料表是二維表",
      "資料表的行列可以互換",
      "資料表的單欄主索引鍵是唯一的",
      "資料表的主索引鍵必須是數值型",
    ],
    referenceAnswer: "資料表是二維表；資料表的單欄主索引鍵是唯一的",
    score: 2,
    image: null,
  },
  {
    id: "nb024",
    stem: "24. 選項語句中，與語句 \" WHERE vend_id = 'DLL01' OR vend_id = 'BRS01' \" 等價的為下列哪一項？",
    type: "single",
    options: [
      "WHERE vend_id = 'DLL01'AND'BRS01'",
      "WHERE vend_id IS 'DLL01'OR'BRS01'",
      "WHERE vend_id %I N% ( 'DLL01''BRS01')",
      "WHERE vend_id I N ( 'DLL01','BRS01')",
    ],
    referenceAnswer: "WHERE vend_id I N ( 'DLL01','BRS01')",
    answerNote: "原題排版可能有缺字；正確 SQL 為 WHERE vend_id IN ('DLL01','BRS01')。",
    score: 2,
    image: null,
  },
  {
    id: "nb025",
    stem: "25. 關於 NoSQL 資料庫，下列敘述哪一項錯誤？",
    type: "single-wrong",
    options: [
      "NoSQL 可以理解為 \" NotOnlySQL \"，是對不同於傳統的關 聯式資料庫（relational database）的統稱",
      "NoSQL 使用 SQL 作為查詢語言，因此具有靈活的資料模型",
      "NoSQL 資料庫都去掉了關聯式資料庫的關聯式特性，這使得資料庫更容易擴展",
      "NoSQL 資料庫都具有非常高的讀寫性能",
    ],
    referenceAnswer: "NoSQL 使用 SQL 作為查詢語言，因此具有靈活的資料模型",
    score: 2,
    image: null,
  },
  {
    id: "nb026",
    stem: "26. 在單因子變異數分析之中，考慮四大飲料品牌之平均銷售量分析， 每一品牌隨機抽取 5 個樣本，下列敘述哪些正確？(複選)",
    type: "multi",
    options: [
      "組間變異 SSB〈Sum of Squares of Between〉的自由度為 3",
      "總變異的自由度為 20",
      "隨機誤差的自由度為 16",
      "如果 F 統計值大於 F 分配查表的臨界值時，則表示四大飲料品牌之平均銷售量不全相等",
    ],
    referenceAnswer:
      "組間變異 SSB〈Sum of Squares of Between〉的自由度為 3；隨機誤差的自由度為 16；如果 F 統計值大於 F 分配查表的臨界值時，則表示四大飲料品牌之平均銷售量不全相等",
    score: 2,
    image: null,
  },
  {
    id: "nb027",
    stem: "27. 下列哪些為平均數的優點？(複選)",
    type: "multi",
    options: [
      "資料無極端值或偏態時，具有代表性",
      "考慮所有觀察值，敏感度較高",
      "適合代數與統計推論計算",
      "不受極端值影響",
    ],
    referenceAnswer: "資料無極端值或偏態時，具有代表性；考慮所有觀察值，敏感度較高；適合代數與統計推論計算",
    score: 2,
    image: null,
  },
  {
    id: "nb028",
    stem: "28. 關於平均數和中位數的定義如下：(1)比較不同教育程度者的收 入，平均數比中位數更合適、(2)可以使用平均數比較兩個班級的 總成績、(3)一次射擊訓練中，甲的平均射擊環數比乙高，那麼甲 一定比乙優秀(4)在資料偏斜程度較大時，中位數比平均數更能代 表整體。上述有幾項說法是正確的？",
    type: "single",
    options: ["1", "2", "3", "4"],
    referenceAnswer: "2",
    score: 2,
    image: null,
  },
  {
    id: "nb029",
    stem: "29. 如附圖所示，關於迴歸分析的敘述，下列哪一項正確？",
    type: "single",
    options: ["選項 A", "選項 B", "選項 C", "選項 D"],
    referenceAnswer: "",
    answerNote: "附圖檔：images/WMbfzYLz.png（請自行放入）；請依圖選正確敘述。",
    score: 2,
    image: "WMbfzYLz.png",
  },
  {
    id: "nb030",
    stem: "30. 簡單隨機抽樣的樣本結果，其單個觀測值與樣本平均數都有對應的 抽樣分佈，關於它們的抽樣分佈，下列敘述哪一項錯誤？",
    type: "single-wrong",
    options: [
      "許多樣本計算出的平均值都是以母體平均值 μ 為中心",
      "一些觀測值平均數的分佈，要比個別觀測值的分佈更接近常 態分佈",
      "如果從母體隨機抽取愈來愈多的觀測值，則這些觀測值平均 數的分佈，遲早會接近常態分佈",
      "只有在樣本數足夠大的情況下，樣本平均數的抽樣分佈才會是近似常態分佈",
    ],
    referenceAnswer:
      "如果從母體隨機抽取愈來愈多的觀測值，則這些觀測值平均 數的分佈，遲早會接近常態分佈",
    score: 2,
    image: null,
  },
  {
    id: "nb031",
    stem: "31. 執行迴歸分析時理想上須先驗證資料是否遵守先決條件，下列敘述哪一項錯誤？",
    type: "single-wrong",
    options: [
      "以 Normal probability plot 驗證獨立性",
      "以 Q-Q plot 驗證常態性",
      "以 Modified Levene Test 驗證一致性",
      "以 Residual time sequence plot 驗證獨立性",
    ],
    referenceAnswer: "以 Normal probability plot 驗證獨立性",
    score: 2,
    image: null,
  },
  {
    id: "nb032",
    stem: "32. 若隨機變數 X 具有卜瓦松分配（Poisson Distribution），單位時間內，事件發生的平均次數為 5，則期望值與變異數分別為下列哪 一項？",
    type: "single",
    options: ["期望值 5，變異數 10", "期望值 5，變異數 5", "期望值 10，變異數 5", "期望值 10，變異數 10"],
    referenceAnswer: "期望值 5，變異數 5",
    score: 2,
    image: null,
  },
  {
    id: "nb033",
    stem: "33. 如附圖所示，某輪胎工廠宣稱其生產之輪胎平均壽命至少 50,000 公里。今某一汽車修理廠欲採購其輪胎，抽取 25 個輪胎檢測其平 均壽命為 49,500 公里，標準差為 500 公里，試利用附圖資料計 算，輪胎平均壽命在 95% 的信心水準下之信賴區間，下列哪一項 正確？",
    type: "single",
    options: ["（49328.9, 49671.1）", "（49293.6, 49706.4）", "（49329.2, 49670.8）", "（49294, 49706）"],
    referenceAnswer: "",
    answerNote: "附圖檔：images/WMDCa5rQ.png（請自行放入）；需對照 t 表或圖中數值。",
    score: 2,
    image: "WMDCa5rQ.png",
  },
  {
    id: "nb034",
    stem: "34. 常用的統計值中，平均數的優點有下列哪些？(複選)",
    type: "multi",
    options: [
      "資料無極端值或偏態時，具有代表性",
      "考慮所有觀察值，敏感度較高",
      "適合代數與統計推論計算",
      "不容易受極端值影響",
    ],
    referenceAnswer: "資料無極端值或偏態時，具有代表性；考慮所有觀察值，敏感度較高；適合代數與統計推論計算",
    score: 2,
    image: null,
  },
  {
    id: "nb035",
    stem: "35. 如附圖所示，為某商品在各時期的銷售價格時，所成交的次數，成 交次數出現最多次的組別是哪一組",
    type: "single",
    options: [
      "第一組銷售價格為 5-10 時，成交次數最多",
      "第三組銷售價格為 15-20 時，成交次數最多",
      "第四組銷售價格為 20-25 時，成交次數最多",
      "第五組銷售價格為 30-35 時，成交次數最多",
    ],
    referenceAnswer: "",
    answerNote: "附圖檔：images/WMrpIuum.png（請自行放入）；請依直方圖眾數組別作答。",
    score: 2,
    image: "WMrpIuum.png",
  },
];
