/** 第三批次題 35–50 */
export default [
  {
    id: "n3-035",
    stem: "35. 已知一組樣本大小為 3 的資料，其樣本平均數為 2，樣本標準差 為 1，如果要評斷此組資料與母體平均數 0 之間的差異程度，其 統計量 t 值，下列哪一項正確？（計算至小數點後二位，四捨五 入）",
    type: "single",
    options: ["1.33", "3.46", "2.12", "-1.44"],
    referenceAnswer: "3.46",
    answerNote: "t=(2-0)/(1/√3)≈3.464→3.46。",
    score: 2,
    image: null,
  },
  {
    id: "n3-036",
    stem: "36. 下列哪一項不是常見的分散度衡量統計量？",
    type: "single",
    options: ["變異係數", "眾數", "平均絕對差", "全距"],
    referenceAnswer: "眾數",
    score: 2,
    image: null,
  },
  {
    id: "n3-037",
    stem: "37. 在 5 個始祖鳥的化石標本中，記錄了股骨與肱骨的長度資料分別 是，股骨：38、56、59、64、74，肱骨：41、63、70、72、84；使 用相關係數分析這組資料，下列敘述哪一項正確？",
    type: "single",
    options: [
      "相關係數為 0.794，說明股骨和肱骨長度正相關",
      "相關係數為 0.794，說明股骨和肱骨長度負相關",
      "相關係數為 0.994，說明股骨和肱骨長度正相關",
      "相關係數為 0.994，說明股骨和肱骨長度負相關",
    ],
    referenceAnswer: "相關係數為 0.994，說明股骨和肱骨長度正相關",
    score: 2,
    image: null,
  },
  {
    id: "n3-038",
    stem: "38. 如附圖所示，統計檢定中，下列哪一項是該理論的虛無假設？",
    type: "single",
    options: ["選項 A", "選項 B", "選項 C", "選項 D"],
    referenceAnswer: "選項 C",
    answerNote: "附圖：WMRVYXkI.png。欲證明 μ>40000 時，H0 常取 μ≤40000。",
    score: 2,
    image: "WMRVYXkI.png",
  },
  {
    id: "n3-039",
    stem: "39. 在 150 筆交易資料中，若想知道購買麵包的人會不會也購買牛奶，經由調查發現購買麵包的交易共有 80 筆，買麵包同時也會買牛奶的交易有 50 筆，關於支持度（support）和信賴度 （confidence）的計算哪一項正確？",
    type: "single",
    options: [
      "支持度 53.3%、信賴度 33.3%",
      "支持度 33.3%、信賴度 53.3%",
      "支持度 33.3%、信賴度 62.5%",
      "支持度 62.5%、信賴度 33.3%",
    ],
    referenceAnswer: "支持度 33.3%、信賴度 62.5%",
    score: 2,
    image: null,
  },
  {
    id: "n3-040",
    stem: "40. 資料探勘中將預測結果與真實值進行比較，下列敘述哪些正確？ (複選)",
    type: "multi",
    options: [
      "對感興趣的類別作了正確的分類稱正確陽性 True Positive （TP）",
      "真陽性比率稱為特異性（specificity）",
      "對不感興趣的類別作了正確的分類稱正確陰性 True Negative（TN）",
      "真陰性比率稱為靈敏度（sensitivity）",
    ],
    referenceAnswer: "對感興趣的類別作了正確的分類稱正確陽性 True Positive （TP）；對不感興趣的類別作了正確的分類稱正確陰性 True Negative（TN）",
    score: 2,
    image: null,
  },
  {
    id: "n3-041",
    stem: "41. 集群與分類的不同在於，集群所要求劃分的類是未知的。 集群分 析計算方法主要有：階層的方法（hierarchical method）、分割方 法（partitioning method）、基於密度的方法（density-based method）、基於網格的方法（grid-based method）、基於模型的方 法（model-based method）等。下列哪些演算法是利用統計學定義 的距離進行度量？(複選)",
    type: "multi",
    options: [
      "階層的方法（hierarchical method）",
      "基於模型的方法（model-based method）",
      "基於密度的方法（density-based method）",
      "分割方法（partitioning method）",
    ],
    referenceAnswer:
      "階層的方法（hierarchical method）；基於密度的方法（density-based method）；分割方法（partitioning method）",
    score: 2,
    image: null,
  },
  {
    id: "n3-042",
    stem: "42. 如附圖所示，試計算出附圖表格內的吉尼指數（Gini 指數），下列哪一項正確？",
    type: "single",
    options: ["1", "1.5", "0", "0.5"],
    referenceAnswer: "0",
    answerNote: "附圖：WMXLg2UW.png。節點純化時 Gini=0。",
    score: 2,
    image: "WMXLg2UW.png",
  },
  {
    id: "n3-043",
    stem: "43. 如附圖所示，附圖中交易資料計算 { whole milk , other vegetables} 的支持度，下列哪一項正確？",
    type: "single",
    options: ["0.6", "0.3", "0.2", "0.18"],
    referenceAnswer: "0.2",
    answerNote: "附圖：WMTjLiOC.png。10 筆交易中 2 筆同時含兩項，支持度 2/10=0.2。",
    score: 2,
    image: "WMTjLiOC.png",
  },
  {
    id: "n3-044",
    stem: "44. 關於階層集群，下列哪一項不是常用的群間距離度量？",
    type: "single",
    options: [
      "組平均距離（group average）法",
      "最短距離（single linkage）法",
      "最長距離（complete linkage）法",
      "最佳距離（optimal linkage）法",
    ],
    referenceAnswer: "最佳距離（optimal linkage）法",
    score: 2,
    image: null,
  },
  {
    id: "n3-045",
    stem: "45. 關於決策樹（dicision trees）的基本概念，下列敘述哪一項錯誤？",
    type: "single-wrong",
    options: [
      "決策樹是功能強大的預測工具",
      "決策樹不是分類的工具",
      "決策樹資料探勘（Data Mining）包含了分析者認為與決策關於的變數，以及這些變數對預測結果的能力",
      "在資料探勘（Data Mining）的領域中，決策樹被認為是一種樹狀結構的規則",
    ],
    referenceAnswer: "決策樹不是分類的工具",
    score: 2,
    image: null,
  },
  {
    id: "n3-046",
    stem: "46. 下列哪一項不是處理缺失值的方法？",
    type: "single",
    options: ["直接刪除缺失值", "對缺失值進行手工填補", "將缺失值標記為異常值", "使用模型來預測缺失值"],
    referenceAnswer: "將缺失值標記為異常值",
    score: 2,
    image: null,
  },
  {
    id: "n3-047",
    stem: "47. 關於決策樹的敘述，下列哪一項錯誤？",
    type: "single-wrong",
    options: [
      "決策樹是功能強大的分類和預測工具",
      "構建模型的成本低是決策樹的優點之一",
      "決策樹可以輸出多個屬性",
      "決策樹的結構是一種類似流程圖的樹結構",
    ],
    referenceAnswer: "決策樹可以輸出多個屬性",
    score: 2,
    image: null,
  },
  {
    id: "n3-048",
    stem: "48. 下列哪一個集群（clustering）技術，最適合處理任意形狀與大小的集群問題？",
    type: "single",
    options: ["階層式集群法", "k-means", "決策樹", "以密度為基礎的集群法"],
    referenceAnswer: "以密度為基礎的集群法",
    score: 2,
    image: null,
  },
  {
    id: "n3-049",
    stem: "49. 異常值通常是指一個偶發的數值，與其他的測量值相差甚遠，可使用下列哪一項統計量判別異常值？",
    type: "single",
    options: ["標準差", "相關係數", "判定係數", "變異係數"],
    referenceAnswer: "標準差",
    score: 2,
    image: null,
  },
  {
    id: "n3-050",
    stem: "50. 將原始資料進行清理、變換、縮減…等，是在下列哪一步驟中的任務？",
    type: "single",
    options: ["資料前處理", "頻繁物項集探勘", "資料探勘流程", "分類和預測"],
    referenceAnswer: "資料前處理",
    score: 2,
    image: null,
  },
];
