/** 新匯入題 1–17 */
export default [
  {
    id: "nb001",
    stem: "1. 資料採礦社群網站 KDNuggets 對使用者所做的調查中，下列哪一 項不是處理 Big data 的常見軟體工具？",
    type: "single",
    options: ["Word", "SQL", "R", "Python"],
    referenceAnswer: "Word",
    score: 2,
    image: null,
  },
  {
    id: "nb002",
    stem: "2. 商業問題中，希望能將顧客群中屬性相似的顧客聚集在一起，但事先並不清楚各群的樣貌時，資料科學家通常可以採用下列哪一項分 析方法？",
    type: "single",
    options: [
      "分類及類別的機率估計（classification）",
      "迴歸（regression）",
      "相似度分析（similarity matching）",
      "集群（clustering）",
    ],
    referenceAnswer: "集群（clustering）",
    score: 2,
    image: null,
  },
  {
    id: "nb003",
    stem: "3. 關於量化模型，下列哪一項正確？",
    type: "single",
    options: [
      "獨立變數已知或在決策者控制之下一定是敘述性模型",
      "線性規劃屬於敘述性模型",
      "函數 f〈.〉 的型式未知且缺乏定義是預測性模型",
      "計劃評核術是規範性模型",
    ],
    referenceAnswer: "計劃評核術是規範性模型",
    score: 2,
    image: null,
  },
  {
    id: "nb004",
    stem: "4. 關於資料探勘流程，下列哪些敘述正確？(複選)",
    type: "multi",
    options: [
      "資料探勘通常是一次性任務，一般不需要重複循環這六個步驟",
      "資料探勘一般需要六個流程：商業理解、資料理解、資料準備、建模、評估、發佈",
      "資料探勘項目只需要資料探勘工程師即可完成",
      "資料探勘的結果評估需要從商業價值方面考慮",
    ],
    referenceAnswer:
      "資料探勘一般需要六個流程：商業理解、資料理解、資料準備、建模、評估、發佈；資料探勘的結果評估需要從商業價值方面考慮",
    score: 2,
    image: null,
  },
  {
    id: "nb005",
    stem: "5. CRISP-DM 資料探勘流程包括下列六項：(1)資料準備、(2)資料理解、(3)評估與測試、(4)模式建立、(5)商業理解、(6)部署應用， 其正確流程步驟哪一項正確？",
    type: "single",
    options: ["521346", "512436", "512346", "521436"],
    referenceAnswer: "521346",
    score: 2,
    image: null,
  },
  {
    id: "nb006",
    stem: "6. 若要符合下述情境的 SQL 指令「找出 Product 資料表中設計日期 為 103 年 10 月 2 日之前（包括 103 年 10 月 2 日）所有資料，建議 日期格式以（'月/日/西元年'）為主」，下列哪一項正確？",
    type: "single",
    options: [
      "SELECT * FROM Product WHERE DesignDate <= '10/2/2014'",
      "SELECT DesignDate FROM Product WHERE '10/2/2014'",
      "SELECT * FROM Product WHERE DesignDate => '10/2/2014'",
      "UPDATE * FROM Product WHERE DesignDate => '10/2/2014'",
    ],
    referenceAnswer: "SELECT * FROM Product WHERE DesignDate <= '10/2/2014'",
    score: 2,
    image: null,
  },
  {
    id: "nb007",
    stem: "7. 如附圖所示，附圖中之 SQL 語法敘述，下列選項哪一項最貼近全 意？",
    type: "single",
    options: [
      "找出 emp 資料表內 dname 欄位是 Research 的資料列，並 對該些資料列的 sal 欄位進行更新的動作，調整為原 sal 的 1.05 倍",
      "子查詢內先在 dept 資料表中找出 dname 為 Research 的 deptno 值，再將這些 deptno 值回傳到父查詢，父查詢為 更新 emp 資料表，找出 emp 資料表的 deptno 欄位符合子 查詢回傳結果的資料列，並將該些資料列的 sal 欄位值調 整成原值的 1.05 倍",
      "更新資料表 emp，對其所有資料列中的 sal 欄位值都進行 更新動作，調整幅度為原 sal 的 1.05 倍",
      "子查詢內先在 emp 資料表中找出 dname 為 Research 的 deptno 值，再將這些 deptno 值回傳到父查詢，父查詢為 更新 dept 資料表，找出 dept 資料表的 deptno 欄位符合 子查詢回傳結果的資料列，並將該些資料列的 sal 欄位值 調整成原值的 1.05 倍",
    ],
    referenceAnswer:
      "子查詢內先在 dept 資料表中找出 dname 為 Research 的 deptno 值，再將這些 deptno 值回傳到父查詢，父查詢為 更新 emp 資料表，找出 emp 資料表的 deptno 欄位符合子 查詢回傳結果的資料列，並將該些資料列的 sal 欄位值調 整成原值的 1.05 倍",
    answerNote: "附圖檔：images/WMPEWKkA.png（請自行放入）。",
    score: 2,
    image: "WMPEWKkA.png",
  },
  {
    id: "nb008",
    stem: "8. 下列哪一項資料不是非結構化資料？",
    type: "single",
    options: ["HTML 格式的文本資料", "XML 格式的文本資料", "空間資料", "影像資料"],
    referenceAnswer: "空間資料",
    answerNote: "若課程對 HTML/XML 歸類不同，請以教師公告為準。",
    score: 2,
    image: null,
  },
  {
    id: "nb009",
    stem: "9. 每日股票交易價格，可視為下列哪一項有序資料？",
    type: "single",
    options: ["時間（temporal）資料", "次序（sequential）資料", "空間（spatial）資料", "基因序列（genetic sequence）資料"],
    referenceAnswer: "時間（temporal）資料",
    score: 2,
    image: null,
  },
  {
    id: "nb010",
    stem: "10. 關於 XML 的敘述，下列哪一項錯誤？",
    type: "single-wrong",
    options: [
      "XML 與 HTML 都是非結構化資料",
      "HTML 用來傳輸和儲存資料，而 XML 被用來顯示資料",
      "通過 XML，可以在不同的系統之間輕鬆地交換資料",
      "XML 允許創作者定義自己的標籤和文檔結構",
    ],
    referenceAnswer: "HTML 用來傳輸和儲存資料，而 XML 被用來顯示資料",
    score: 2,
    image: null,
  },
  {
    id: "nb011",
    stem: "11. 關於 JSON 的敘述，下列哪一項錯誤？",
    type: "single-wrong",
    options: [
      "JSON 是 JavaScript 的物件表示法（JavaScript Object Notation）",
      "JSON 解析器和 JSON 資料集支援許多不同的程式語言",
      "JSON 非常易於解析",
      "JSON 文本格式在語法上與創建 JavaScript 物件的代碼不同",
    ],
    referenceAnswer: "JSON 文本格式在語法上與創建 JavaScript 物件的代碼不同",
    score: 2,
    image: null,
  },
  {
    id: "nb012",
    stem: "12. 若欲使用 SQL 語言，找出 Product 資料表中設計日期 （designDate）為 95 年 10 月 2 日之前（包括 95 年 10 月 2 日）所有資料，建議日期格式以 '10/2/2006' 為主（'月/日/西元 年'），下列哪一項正確？",
    type: "single",
    options: [
      "SELECT * FROM Product WHERE designDate<='10/2/2006'",
      "SELECT * FROM designDate WHERE Date > 951002",
      "SELECT * FROM designDate WHERE Product <='10/2/2006'",
      "SELECT * FROM Product",
    ],
    referenceAnswer: "SELECT * FROM Product WHERE designDate<='10/2/2006'",
    score: 2,
    image: null,
  },
  {
    id: "nb013",
    stem: "13. 下列哪一項不是常見的 NoSQL 資料儲存方式？",
    type: "single",
    options: [
      "JSON 文件儲存方式",
      "實體關聯儲存方式",
      "鍵值對（key-value pair）儲存方式",
      "節點、邊、關係（relation）等屬性的圖形（graph）結構儲存方式",
    ],
    referenceAnswer: "實體關聯儲存方式",
    score: 2,
    image: null,
  },
  {
    id: "nb014",
    stem: "14. 如附圖所示，已知產品資料表：Product（ProductID, DesignDate, DesignerID），找出產品資料表中不重覆的 DesignerID 資料的 SQL 指令，下列哪一項正確？",
    type: "single",
    options: [
      "SELECT DIFFERENT DesignerID FROM Product",
      "SELECT SINGLE DesignerID FROM Product",
      "SELECT PRECISE DesignerID FROM Product",
      "SELECT DISTINCT DesignerID FROM Product",
    ],
    referenceAnswer: "SELECT DISTINCT DesignerID FROM Product",
    score: 2,
    image: "WMRyrmZj.png",
  },
  {
    id: "nb015",
    stem: "15. 關於資料屬性尺度的範例中，下列哪一項正確？",
    type: "single",
    options: [
      "攝氏溫度是區間尺度",
      "華氏溫度是比例尺度",
      "郵遞區號是順序尺度",
      "年級是名目尺度",
    ],
    referenceAnswer: "攝氏溫度是區間尺度",
    score: 2,
    image: null,
  },
  {
    id: "nb016",
    stem: "16. 在 SQL 語言中，INSERT 指令的功用，下列哪一項正確？",
    type: "single",
    options: ["新增資料", "修改資料", "刪除資料", "沒有此指令"],
    referenceAnswer: "新增資料",
    score: 2,
    image: null,
  },
  {
    id: "nb017",
    stem: "17. 關於比例（ratio）屬性值，擁有下列哪些運算性質？(複選)",
    type: "multi",
    options: ["不等性（distinctness）", "順序性（order）", "可加性（addition）", "可乘性（multiplication）"],
    referenceAnswer: "不等性（distinctness）；順序性（order）；可加性（addition）；可乘性（multiplication）",
    score: 2,
    image: null,
  },
];
